### ISSUE TITLE
Add option of Timestamp in milliseconds

### ISSUE THREAD

**Issue by alexgarciab** [stape-io/timestamp-converter-variable#3]
Would it be possible to add an option to this tag to get the value of Timestamp in milliseconds?

For example, for the creation of the "fbc" (Click ID) parameter in Facebook, the Timestamp is required in milliseconds: https://developers.facebook.com/docs/marketing-api/conversions-api/parameters/fbp-and-fbc

**Comment by Bukashk0zzz** [comment]
We do not plan to add such functionality
